//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.Составы_заказа = new HashSet<Составы_заказа>();
        }
    
        public int номер_заказа { get; set; }
        public System.DateTime дата_заказа { get; set; }
        public Nullable<System.DateTime> дата_доставки { get; set; }
        public int пункт_выдачи { get; set; }
        public string логин_клиента { get; set; }
        public int код_для_получения { get; set; }
        public int статус_заказа { get; set; }
        public int стоимость { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пункты_выдачи Пункты_выдачи { get; set; }
        public virtual Статусы Статусы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Составы_заказа> Составы_заказа { get; set; }
    }
}
