//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукты()
        {
            this.Составы_заказа = new HashSet<Составы_заказа>();
        }
    
        public string артикул { get; set; }
        public string наименование { get; set; }
        public int ед_изм { get; set; }
        public int стоимость { get; set; }
        public int макс_скидка { get; set; }
        public int производитель { get; set; }
        public int id_поставщика { get; set; }
        public int категория { get; set; }
        public int скидка { get; set; }
        public int колво_склад { get; set; }
        public int мин_склад { get; set; }
        public string описание { get; set; }
        public string изображение { get; set; }
    
        public virtual Единицы_измерения Единицы_измерения { get; set; }
        public virtual Категории Категории { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        public virtual Производители Производители { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Составы_заказа> Составы_заказа { get; set; }
    }
}
